version: "3"
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=secretpassw0rd
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
    pgdata: 